name: Fetch activity
description: Inventory user activity
inputs:
  path:
    description: The file path to the database
    default: /tmp/db.json
    required: false
    type: string
secrets:
  token: 
    description: Token used to execute next workflow

runs:
  using: composite
  steps: 
    - uses: actions/checkout@v3
        with:
          path: main
          repository: oss-tooling/user-inactivity
    - uses: actions/checkout@v3
        with:
          ref: activity
          path: activity
          repository: oss-tooling/user-inactivity
    - name: Stage db.json
      run: |
        if test -f "${{ github.workspace }}/activity/db.json"; then 
          mv ${{ github.workspace }}/activity/db.json ${{ github.workspace }}/main/db.json
        fi
      shell: bash
    - name: Install dependencies
      run: npm install
      working-directory: ${{ github.workspace }}/main
      shell: bash
    - name: Collect Audit Log
      run: node src/audit.js && mv db.json ${{ inputs.path }}
      working-directory: ${{ github.workspace }}/main
      shell: bash
    - name: Update db.json
      run: |
        rm -rf db.json
        mv $OUTFILE ./db.json
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add db.json
        git commit -m 'adding latest audit entries'
        git push
      working-directory: ${{ github.workspace }}/activity
      shell: bash
    - name: Trigger Next Workflow
      run: gh workflow run --repo ${{ github.repository }} $WORKFLOW_FILENAME
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.DEVOPS_BOT_PAT }}
        WORKFLOW_FILENAME: contributions.yml
