name: Fetch activity
description: Inventory user activity
inputs:
  org:
    description: the github organization to audit
  path:
    description: The file path to the database
    default: /tmp/db.json
    required: false
    type: string
  APP_ID: 
    description: the app id
  APP_PRIVATE_KEY:
    description: the app private key
  APP_INSTALLATION_ID:
    description: the app installation id
runs:
  using: composite
  steps: 
    - name: get token
      id: get-token
      uses: getsentry/action-github-app-token@v2
      with:
        app_id: ${{ inputs.APP_ID }}
        private_key: ${{ inputs.APP_PRIVATE_KEY }}
    - uses: actions/checkout@v3
      with:
        path: main
        repository: oss-tooling/user-inactivity
    - uses: actions/checkout@v3
      with:
        ref: activity
        path: activity
    - name: Stage db.json
      run: |
        if test -f "${{ github.workspace }}/activity/db.json"; then 
          mv ${{ github.workspace }}/activity/db.json ${{ github.workspace }}/main/db.json
        fi
      shell: bash
    - name: Install dependencies
      run: npm install
      working-directory: ${{ github.workspace }}/main
      shell: bash
    - name: Collect Audit Log
      run: node src/audit.js && mv db.json ${{ inputs.path }}
      working-directory: ${{ github.workspace }}/main
      shell: bash
      env:
        GH_APP_ID: ${{ inputs.APP_ID }}
        GH_APP_PRIVATE_KEY: ${{ inputs.APP_PRIVATE_KEY }}
        GH_APP_INSTALLATION_ID: ${{ inputs.APP_INSTALLATION_ID }}
        ORG: ${{ inputs.org }}
    - name: Update db.json
      run: |
        if test -f db.json; then 
          rm -rf db.json
        fi
        mv ${{ github.workspace }}/main/db.json ./db.json
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add db.json
        git commit -m 'adding latest audit entries'
        git push
      working-directory: ${{ github.workspace }}/activity
      shell: bash
