name: Fetch audit log activity

on:
  schedule:
    - cron: "0 1 * * 1-6"
  workflow_dispatch:

jobs:
  fetch-audit-log:
    runs-on:
      - self-hosted
      - activity
    env:
      GH_ADMIN_TOKEN: ${{ secrets.DEVOPS_BOT_PAT }}
      ORG: ${{ github.repository_owner }}
      OUTFILE: /tmp/db.json
    steps:
      - name: Cleanup Workspace
        uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/checkout@v2
        with:
          ref: activity
          path: activity
      - name: Stage db.json
        run: mv ${{ github.workspace }}/activity/db.json ${{ github.workspace }}/main/db.json
      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/main
      - name: Collect Audit Log
        run: node src/audit.js && mv db.json $OUTFILE
        working-directory: ${{ github.workspace }}/main
      - name: Update db.json
        run: |
          rm -rf db.json
          mv $OUTFILE ./db.json
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add db.json
          git commit -m 'adding latest audit entries'
          git push
        working-directory: ${{ github.workspace }}/activity
      - name: Trigger Next Workflow
        run: gh workflow run --repo ${{ github.repository }} $WORKFLOW_FILENAME
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_BOT_PAT }}
          WORKFLOW_FILENAME: contributions.yml
