name: Remove Inactive Users

on:
  schedule:
    - cron: "15 12 * * 4"
  workflow_dispatch:

jobs:
  remove-users:
    runs-on: ubuntu-latest
    env:
      GH_ADMIN_TOKEN: ${{ secrets.DEVOPS_BOT_PAT }}
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      ORG: ${{ github.repository_owner }}
      REPO: 'github-inactive-user-mentions'
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/checkout@v2
        with:
          ref: activity
          path: activity
      - name: Stage db.json
        run: mv ${{ github.workspace }}/activity/db.json ${{ github.workspace }}/main/db.json
      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/main
      - name: Remove Inactive Users
        run: node src/kick.js
        working-directory: ${{ github.workspace }}/main
