name: Reconcile Database

on:
  schedule:
    - cron: "15 18 * * 0"
  workflow_dispatch:

jobs:
  reconcile-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/checkout@v2
        with:
          ref: activity
          path: activity
      - name: Stage db.json
        run: mv ${{ github.workspace }}/activity/db.json ${{ github.workspace }}/main/db.json
      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/main
      - name: Reconcile Users
        run: node src/reconcile.js && mv db*.json ${{ github.workspace }}/activity/
        working-directory: ${{ github.workspace }}/main
      - name: Update db.json
        run: |
          rm -rf backup_dbs/$(ls db-*)
          mv db-* backup_dbs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add db.json backup_dbs
          git commit -m 'reconciled db.json'
          git push
        working-directory: ${{ github.workspace }}/activity
